name: Set Bot Up

on: workflow_dispatch

jobs: 
  build:
    name: Setting up Bot Environment
    runs-on: ubuntu-latest
    steps:
      - name: Preparing Source Code
        uses: actions/checkout@v2

      - name: The bot is ready and availabe for 6 hours!
        run: while true; do "running"; sleep 100; done
