name: Set Bot Up

on: workflow_dispatch

jobs: 
  build:
    name: Setting up Bot Environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-cli.txt
      - name: Getting Credentials 
        run: |
          pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib 
          python3 generate_drive_token.py
      - name: Building Image
        run: docker build . -t mirror-bot
      - name: Running the bot
        run: docker run mirror-bot
