name: Telegram Bot Set Up

on: workflow_dispatch

jobs: 
  build:
    name: Setting up Bot Environment
    runs-on: ubuntu-latest
    steps:
      - name: Preparing Source Code
        uses: actions/checkout@v2
      - name: Installing Python3
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-cli.txt
      - name: Getting Credentials 
        run: |
          pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib 
          python3 generate_drive_token.py
      - name: Generating Telegram Credentials
        run: python3 generate_string_session.py
      - name: Building Bot
        run: docker build . -t mirror-bot
      - name: Running the bot
        run: docker run mirror-bot
      - name: The bot is ready and availabe for 6 hours! Join t.me/drivetalk for any question
        run: while true; do sleep 100; done
